defaults:
  - _self_
  - exp: baseline

# ["HanChuan", "HongHu"]
dataset_name: "HanChuan"

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data

train_samples: 30
val_samples: 10

seed: 42
epoch: 2
lr: 0.0003

split_image: false

swanlab: "offline"

hydra:
  job:
    chdir: true
