model:
  name: "beta_v5_2"
  instance:
    _target_: models.beta.v5_2.model.Model

epoch: 200

optimizer:
  label_smoothing: 0.1
  weight_decay: 1e-4

loss:
  instance:
    _target_: models.beta.v5_2.model.LossCalculator

src:
  - train.py
  - models/beta/v5_2/

lr_scheduler:
  name: "cosine"
  warmup_epochs: 10
  min_lr: 1e-6
