model:
  name: "WaveletDownsampler-As-AvgPool"
  instance:
    _target_: models.v3.WaveletDownsampler.Model

epoch: 200

optimizer:
  label_smoothing: 0.1

src:
  - train.py
  - models/v3/WaveletDownsampler.py
