model:
  name: "beta_v5_2"
  instance:
    _target_: models.v5.main.Model

epoch: 200

optimizer:
  label_smoothing: 0.1
  weight_decay: 1e-4

loss:
  instance:
    _target_: models.v5.main.LossCalculator

src:
  - train.py
  - models/v5/

lr_scheduler:
  name: "cosine"
  warmup_epochs: 10
  min_lr: 1e-6
